DELIMITER // 
CREATE PROCEDURE spFetchProjects()
BEGIN
	SELECT WORK.WORK_ID, WORK.WORK_NAME, WORK.WORK_DESCRIPTION, WORK.WORK_COVER_IMAGE, CATEGORY.CATEGORY_DESCRIPTION
    FROM WORK 
    INNER JOIN CATEGORY ON WORK.CATEGORY_ID = CATEGORY.CATEGORY_ID ORDER BY WORK.WORK_ID;
END //
DELIMITER ;