DELIMITER // 
CREATE PROCEDURE spInsertProject(
    IN WORK_NAME VARCHAR(200),
    IN WORK_DESCRIPTION VARCHAR(5000),
    IN WORK_CATEGORY INT(11),
    IN COVER_IMAGE VARCHAR(500)
)
BEGIN
    INSERT INTO WORK (WORK_NAME, WORK_DESCRIPTION, CATEGORY_ID, WORK_COVER_IMAGE)
    VALUES (WORK_NAME, WORK_DESCRIPTION, WORK_CATEGORY, COVER_IMAGE);
    SELECT  LAST_INSERT_ID() AS 'insertId';
END //
DELIMITER ;