DELIMITER // 
CREATE PROCEDURE spInsertProject(
    IN WORK_NAME VARCHAR(200),
    IN WORK_DESCRIPTION VARCHAR(5000),
    IN WORK_CATEGORY INT(11)
)
BEGIN
    INSERT INTO WORK (WORK_NAME, WORK_DESCRIPTION, CATEGORY_ID)
    VALUES (WORK_NAME, WORK_DESCRIPTION, WORK_CATEGORY);
END //
DELIMITER ;