DELIMITER // 
CREATE PROCEDURE spFetchCategoryById(IN CATEGORY_ID INT)
BEGIN
	SELECT CATEGORY.CATEGORY_ID, CATEGORY.CATEGORY_DESCRIPTION 
    FROM CATEGORY
    WHERE CATEGORY.CATEGORY_ID = CATEGORY_ID;
END // 
DELIMITER ;