DELIMITER // 
CREATE PROCEDURE spUpdateCategory(
    IN CATEGORY_DESCRIPTION VARCHAR(500),
    IN CATEGORY_ID INT(11)
)
BEGIN
    UPDATE 
        CATEGORY 
    SET 
        CATEGORY_DESCRIPTION = CATEGORY_DESCRIPTION
    WHERE 
        CATEGORY.CATEGORY_ID = CATEGORY_ID;
END //
DELIMITER ;